# Global logging configuration
#����ļ�ֻҪ����classpathĿ¼�о��� ����resources�� ϵͳ�Զ����� ��Ҫ������pom�����log4j������
log4j.rootLogger=ERROR, stdout
# MyBatis logging configuration...
log4j.logger.com.zhang.hospital.dao=DEBUG
# Console output...
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p [%t] %m%n
 

